from datetime import datetime, timezone

NOW = datetime.now(timezone.utc).isoformat()

MOS_URL = "https://mathematical-operating-system-production.up.railway.app"


def _svc(slug, name, tagline, description, category, tier, accent,
         benefits, proof_of_work, worth, endpoints, tags,
         repo=None, homepage=None, base_url=None):
    return {
        "slug": slug,
        "name": name,
        "tagline": tagline,
        "description": description,
        "category": category,
        "tier": tier,
        "accent": accent,
        "status": "online",
        "base_url": base_url or f"/gateway/{slug}",
        "benefits": benefits,
        "proof_of_work": proof_of_work,
        "worth": worth,
        "endpoints": endpoints,
        "tags": tags,
        "repo": repo,
        "homepage": homepage,
        "created_at": NOW,
        "updated_at": NOW,
    }


ARCHIVED_MAIN_SLUGS = [
    "dmension", "hydrogenoid", "polysculpt", "fill-theory",
    "cosmic-forces", "3dpstudio", "uuon-c-bot",
]


SEED_SERVICES = [
    # ── MOS DOMAIN ──────────────────────────────────────────────────────────
    _svc(
        slug="mos-credits",
        name="MOS Credit System",
        tagline="PIEZ-powered credit economy for the UUON stack",
        description=(
            "The Mathematical Operating System's credit layer. "
            "Buy, consume, transfer and pool credits backed by PIEZ tokens on Base Mainnet. "
            "Every transaction is atomic, audited, and Neon-persisted."
        ),
        category="MOS • Economy",
        tier="industrial",
        accent="gold",
        benefits=[
            "PIEZ-to-credit conversion on Base Mainnet",
            "Atomic transactions with full rollback on failure",
            "Duplicate tx_hash rejection (no double-spend)",
            "Team credit pools for B2B",
            "Cross-platform account linking (Telegram, Discord)",
        ],
        proof_of_work=[
            {"metric": "DB", "value": "Neon PostgreSQL (7 tables live)"},
            {"metric": "chains", "value": "Base, Arbitrum, Optimism, Polygon"},
            {"metric": "UUON contract", "value": "0x29b056EF63867BECe07DA46c470aC168154EF275"},
            {"metric": "PIEZ contract", "value": "0xfb9c83432331EAf6f4a9D9488828823587d6f3da"},
            {"metric": "uptime", "value": "live on Railway"},
        ],
        worth={
            "tier_label": "Industrial",
            "price_unit": "per package",
            "price": "10–500 PIEZ",
            "sla": "99.95%",
            "notes": "Starter 1k cr / Pro 10k cr / Enterprise 100k cr",
        },
        endpoints=[
            {"id": "mos-packages", "method": "GET", "path": "/api/credits/packages",
             "summary": "List available credit packages", "auth": "none",
             "request_sample": {},
             "response_sample": {"packages": {"starter": {"credits": 1000, "piez_cost": 10}}}},
            {"id": "mos-init", "method": "POST", "path": "/api/credits/init",
             "summary": "Create user account (100 free credits)", "auth": "api_key",
             "request_sample": {"wallet_address": "0xYOUR_WALLET"},
             "response_sample": {"status": "success", "account": {"credits_balance": "100.00000000"}}},
            {"id": "mos-balance", "method": "GET", "path": "/api/credits/balance",
             "summary": "Get credit balance", "auth": "api_key",
             "request_sample": {},
             "response_sample": {"credits_balance": "100100.00000000", "tier": "enterprise"}},
            {"id": "mos-buy", "method": "POST", "path": "/api/credits/buy",
             "summary": "Purchase credits with PIEZ", "auth": "api_key",
             "request_sample": {"packageName": "enterprise", "txHash": "0x...", "chain": "base"},
             "response_sample": {"status": "success", "creditsAdded": 100000}},
            {"id": "mos-consume", "method": "POST", "path": "/api/credits/consume",
             "summary": "Deduct credits for API usage", "auth": "api_key",
             "request_sample": {"cost_type": "shape_query", "quantity": 1, "credits": 5},
             "response_sample": {"status": "success", "creditsUsed": 5}},
            {"id": "mos-transfer", "method": "POST", "path": "/api/credits/transfer",
             "summary": "Transfer credits to another user", "auth": "api_key",
             "request_sample": {"to_user_id": "user_002", "credits": 50},
             "response_sample": {"status": "success", "transferred": 50}},
            {"id": "mos-pool", "method": "POST", "path": "/api/credits/create-pool",
             "summary": "Create a team credit pool", "auth": "api_key",
             "request_sample": {"pool_name": "Dev Team", "credits": 500},
             "response_sample": {"status": "success", "poolId": "pool_xxx"}},
        ],
        tags=["mos", "credits", "piez", "base", "economy"],
        homepage=MOS_URL,
        base_url=MOS_URL,
    ),
    _svc(
        slug="mos-shapes",
        name="MOS Genesis Shapes",
        tagline="32 mathematical objects anchored to Base Mainnet",
        description=(
            "32 genesis shapes from the Mathematical Operating System. "
            "SHA-256 as a surface. The Bloch sphere as a volume. Kyber as a lattice field. "
            "Genesis hash anchored to Base Mainnet block 47259953."
        ),
        category="MOS • Geometry",
        tier="industrial",
        accent="cyan",
        benefits=[
            "32 shapes across 10 mathematical families",
            "Genesis hash anchored to Base Mainnet block 47259953",
            "Quantum gates, quantum states, financial surfaces, AI geometry",
            "Full parametric control (a–f, uSegments, vSegments)",
            "PIEZ-gated compute endpoints",
        ],
        proof_of_work=[
            {"metric": "Genesis hash", "value": "cf114022...3ca04"},
            {"metric": "Anchored", "value": "Base Mainnet · Block 47259953"},
            {"metric": "Families", "value": "10 (crypto, quantum, AI, financial, market)"},
        ],
        worth={
            "tier_label": "Industrial",
            "price_unit": "per compute call",
            "price": "5–50 credits",
            "sla": "99.95%",
            "notes": "Credits purchased via MOS Credit System",
        },
        endpoints=[
            {"id": "shapes-list", "method": "GET", "path": "/api/shapes",
             "summary": "List all 32 genesis shapes", "auth": "none",
             "request_sample": {},
             "response_sample": {"shapes": [{"shapeId": "sha256_compression_function", "family": "cryptographic_hash"}]}},
            {"id": "shapes-get", "method": "GET", "path": "/api/shapes/{shapeId}",
             "summary": "Get full metadata for a shape", "auth": "none",
             "request_sample": {"shapeId": "qubit_bloch_sphere"},
             "response_sample": {"shapeId": "qubit_bloch_sphere", "energy": 8.1e31}},
        ],
        tags=["mos", "shapes", "geometry", "quantum", "base"],
        homepage=MOS_URL,
        base_url=MOS_URL,
    ),

    # ── CLOUUD DOMAIN ────────────────────────────────────────────────────────
    _svc(
        slug="clouud-aeye",
        name="Clouud Æye",
        tagline="Structured intelligence engine with lattice services",
        description="Autonomous decision-making C engine paired with lattice-based reasoning, real-time analytics and pattern extraction.",
        category="Clouud • Intelligence",
        tier="industrial",
        accent="cyan",
        benefits=["Autonomous C-engine decisions in <5ms", "Lattice reasoning across cross-domain data",
                  "Real-time analytics stream (SSE + WebSocket)", "Pattern extraction with symbolic output"],
        proof_of_work=[{"metric": "p50 latency", "value": "3.2 ms"}, {"metric": "uptime (90d)", "value": "99.982%"}],
        worth={"tier_label": "Industrial", "price_unit": "per 1k calls", "price": "$0.40", "sla": "99.95%", "notes": ""},
        endpoints=[
            {"id": "aeye-decide", "method": "POST", "path": "/decide",
             "summary": "Run autonomous decision through C-engine", "auth": "api_key",
             "request_sample": {"context": "market-shift", "signals": [0.42, 0.87, 0.11]},
             "response_sample": {"decision": "hold", "confidence": 0.83}},
            {"id": "aeye-lattice", "method": "POST", "path": "/lattice/reason",
             "summary": "Reason across symbolic lattice node graph", "auth": "api_key",
             "request_sample": {"nodes": ["sun", "phi", "prime"], "depth": 3},
             "response_sample": {"path": ["sun", "phi", "spiral", "prime"], "score": 0.94}},
            {"id": "aeye-patterns", "method": "GET", "path": "/patterns/latest",
             "summary": "Fetch latest extracted patterns", "auth": "api_key",
             "request_sample": {"limit": 5},
             "response_sample": {"patterns": [{"id": "p_001", "kind": "fibonacci"}]}},
        ],
        tags=["intelligence", "lattice", "realtime", "core"],
        repo="https://github.com/UUON-Foundation/API-Gateway",
    ),
    _svc(
        slug="clouud-reducer",
        name="Clouud Reducer",
        tagline="99% dimensional & data-reduction engine (PCA / SVD / UMAP / t-SNE)",
        description="High-throughput data-reduction service. Reduces high-dimensional vectors, tabular data and time-series into compact faithful representations.",
        category="Clouud • Reduction",
        tier="industrial",
        accent="cyan",
        benefits=["PCA / SVD / UMAP / t-SNE in one interface", "Batchable up to 100k rows",
                  "99% lattice state compression", "20x query speed advantage"],
        proof_of_work=[{"metric": "compression", "value": "99%"}, {"metric": "speed gain", "value": "20x"},
                       {"metric": "avg reduction time", "value": "62 ms"}],
        worth={"tier_label": "Industrial", "price_unit": "per 1M rows", "price": "$0.80", "sla": "99.95%", "notes": ""},
        endpoints=[
            {"id": "red-pca", "method": "POST", "path": "/reduce/pca",
             "summary": "PCA over a matrix", "auth": "api_key",
             "request_sample": {"matrix": [[1, 2, 3], [4, 5, 6]], "k": 2},
             "response_sample": {"components": [[0.7, 0.4]], "explained_variance": [0.91]}},
            {"id": "red-umap", "method": "POST", "path": "/reduce/umap",
             "summary": "UMAP projection", "auth": "api_key",
             "request_sample": {"vectors": [[0.1, 0.2, 0.3]], "dim": 2},
             "response_sample": {"projection": [[0.12, -0.44]]}},
        ],
        tags=["clouud", "reduction", "compression", "pca"],
        repo="https://github.com/UUON-Foundation/API-Gateway",
    ),
    _svc(
        slug="clouud-vector",
        name="Clouud Vector Index",
        tagline="Sub-millisecond kNN vector search over the lattice",
        description="Approximate nearest-neighbor index optimized for Clouud embeddings. Sub-millisecond kNN lookups.",
        category="Clouud • Search",
        tier="industrial",
        accent="gold",
        benefits=["Sub-millisecond kNN at scale", "HNSW + IVF-PQ under one interface", "recall@10: 0.982"],
        proof_of_work=[{"metric": "p50 lookup", "value": "0.7 ms"}, {"metric": "recall@10", "value": "0.982"}],
        worth={"tier_label": "Industrial", "price_unit": "per 1M queries", "price": "$1.20", "sla": "99.95%", "notes": ""},
        endpoints=[
            {"id": "vec-upsert", "method": "POST", "path": "/index/{name}/upsert",
             "summary": "Upsert vectors into index", "auth": "api_key",
             "request_sample": {"vectors": [{"id": "v1", "values": [0.1, 0.2]}]},
             "response_sample": {"upserted": 1}},
            {"id": "vec-query", "method": "POST", "path": "/index/{name}/query",
             "summary": "kNN query", "auth": "api_key",
             "request_sample": {"vector": [0.1, 0.2], "k": 5},
             "response_sample": {"matches": [{"id": "v1", "score": 0.98}]}},
        ],
        tags=["clouud", "vector", "knn", "search"],
    ),
    _svc(
        slug="clouud-timeseries",
        name="Clouud Time-Series",
        tagline="Compressed symbolic time-series storage & query (12x)",
        description="Store, compress and query time-series streams with 12x lossless symbolic compression.",
        category="Clouud • TSDB",
        tier="enterprise",
        accent="magenta",
        benefits=["Lossless symbolic compression (~12x)", "Ingest at 250k points/sec/node"],
        proof_of_work=[{"metric": "compression ratio", "value": "11.8x"}, {"metric": "ingest peak", "value": "1.2M pts/s"}],
        worth={"tier_label": "Enterprise", "price_unit": "per 1M points", "price": "$0.05", "sla": "99.9%", "notes": ""},
        endpoints=[
            {"id": "ts-write", "method": "POST", "path": "/series/{name}/write",
             "summary": "Write points to a series", "auth": "api_key",
             "request_sample": {"points": [{"t": 1707500000, "v": 42.1}]},
             "response_sample": {"written": 1}},
            {"id": "ts-query", "method": "POST", "path": "/series/{name}/query",
             "summary": "Query time range", "auth": "api_key",
             "request_sample": {"from": 1707500000, "to": 1707600000, "agg": "mean"},
             "response_sample": {"points": [{"t": 1707500060, "v": 41.8}]}},
        ],
        tags=["clouud", "timeseries", "compression"],
    ),
    _svc(
        slug="clouud-symbolic",
        name="Clouud Symbolic Parser",
        tagline="Parse & evaluate UUON symbolic expressions",
        description="Parses UUON symbolic grammar into a lattice AST, evaluates it, returns typed reducible results.",
        category="Clouud • Symbolic",
        tier="research",
        accent="cyan",
        benefits=["Full UUON symbolic grammar", "Deterministic side-effect free evaluation"],
        proof_of_work=[{"metric": "avg parse time", "value": "1.1 ms"}, {"metric": "grammar coverage", "value": "100%"}],
        worth={"tier_label": "Research", "price_unit": "per 1M parses", "price": "$0.50", "sla": "99.5%", "notes": "Free for researchers"},
        endpoints=[
            {"id": "sym-parse", "method": "POST", "path": "/parse",
             "summary": "Parse a UUON symbolic expression", "auth": "api_key",
             "request_sample": {"expr": "phi(spiral(3))"},
             "response_sample": {"ast": {"op": "phi", "args": [{"op": "spiral", "args": [3]}]}}},
            {"id": "sym-eval", "method": "POST", "path": "/eval",
             "summary": "Evaluate expression", "auth": "api_key",
             "request_sample": {"expr": "phi(spiral(3))"},
             "response_sample": {"value": 1.6180339887, "type": "real"}},
        ],
        tags=["clouud", "symbolic", "parser"],
    ),

    # ── B2B ENGINES ──────────────────────────────────────────────────────────
    _svc(
        slug="d13mon4-hash",
        name="D13MON4 Hash Engine",
        tagline="Custom SHA-256 + salt marketplace — buy and sell cryptographic hashes",
        description="Enhanced SHA-256 with custom salt and up to 100k iterations. Hash marketplace with energy cost model.",
        category="B2B • Cryptographic",
        tier="enterprise",
        accent="magenta",
        benefits=["Custom salt + 1k–100k iterations", "Hash marketplace (create → list → sell)", "Energy cost calculation"],
        proof_of_work=[{"metric": "algorithm", "value": "SHA-256 + PBKDF2"}, {"metric": "max iterations", "value": "100,000"}],
        worth={"tier_label": "Enterprise", "price_unit": "per hash", "price": "10 credits", "sla": "99.9%", "notes": ""},
        endpoints=[
            {"id": "hash-create", "method": "POST", "path": "/hash/create",
             "summary": "Create custom hash", "auth": "api_key",
             "request_sample": {"data": "my-data", "iterations": 10000},
             "response_sample": {"hashId": "uuid", "hash": "sha256...", "energyCost": 0.001}},
            {"id": "hash-verify", "method": "POST", "path": "/hash/verify",
             "summary": "Verify hash", "auth": "api_key",
             "request_sample": {"data": "my-data", "hashId": "uuid", "hash": "sha256..."},
             "response_sample": {"valid": True}},
        ],
        tags=["b2b", "hash", "crypto", "marketplace"],
    ),
    _svc(
        slug="depth-engine",
        name="Depth Engine",
        tagline="Real-time depth-map rendering and surface analysis",
        description="GPU-accelerated depth map generation from 2D inputs. Surface normal extraction, occlusion maps, and 3D reconstruction.",
        category="B2B • Visual",
        tier="enterprise",
        accent="orange",
        benefits=["Real-time depth estimation", "Surface normal extraction", "3D reconstruction ready"],
        proof_of_work=[{"metric": "avg latency", "value": "45 ms"}, {"metric": "resolution", "value": "up to 4K"}],
        worth={"tier_label": "Enterprise", "price_unit": "per 1k frames", "price": "$1.20", "sla": "99.9%", "notes": ""},
        endpoints=[
            {"id": "depth-map", "method": "POST", "path": "/depth/map",
             "summary": "Generate depth map from image URL", "auth": "api_key",
             "request_sample": {"url": "https://cdn.uuon.world/sample.jpg"},
             "response_sample": {"depth_map_url": "https://cdn.uuon.world/depth.png", "min": 0.1, "max": 9.8}},
        ],
        tags=["b2b", "depth", "rendering", "3d"],
    ),
    _svc(
        slug="swarm-intelligence",
        name="Swarm Intelligence Engine",
        tagline="Multi-agent coordination and emergent behavior orchestration",
        description="Deploy swarms of lightweight agents that coordinate via stigmergy. ACO, PSO, and custom UUON lattice-swarm algorithms.",
        category="B2B • AI",
        tier="enterprise",
        accent="cyan",
        benefits=["ACO / PSO / lattice-swarm algorithms", "Up to 10k simultaneous agents", "Emergent consensus detection"],
        proof_of_work=[{"metric": "max agents", "value": "10,000"}, {"metric": "consensus time", "value": "<200ms"}],
        worth={"tier_label": "Enterprise", "price_unit": "per swarm-run", "price": "$0.25", "sla": "99.9%", "notes": ""},
        endpoints=[
            {"id": "swarm-run", "method": "POST", "path": "/swarm/run",
             "summary": "Launch a swarm task", "auth": "api_key",
             "request_sample": {"algorithm": "aco", "agents": 100, "task": "pathfind"},
             "response_sample": {"runId": "swarm_001", "status": "running", "eta_ms": 180}},
        ],
        tags=["b2b", "swarm", "multi-agent", "ai"],
    ),
    _svc(
        slug="uuon-shape-tokenizer",
        name="UUON Shape Tokenizer",
        tagline="Shape → ERC-20 token minting pipeline on Base/Arbitrum/Optimism/Polygon",
        description="Convert any UUON mathematical shape into a verifiable ERC-20 token. Includes provenance, SHA-256 fingerprint, and on-chain metadata.",
        category="B2B • Blockchain",
        tier="industrial",
        accent="gold",
        benefits=["ERC-20 minting on Base, Arbitrum, Optimism, Polygon", "SHA-256 provenance fingerprint",
                  "On-chain metadata (rarity, topology, symmetry)"],
        proof_of_work=[{"metric": "chains", "value": "4 (Base, Arbitrum, Optimism, Polygon)"},
                       {"metric": "provenance", "value": "SHA-256 verified"}],
        worth={"tier_label": "Industrial", "price_unit": "per mint", "price": "1–5 PIEZ", "sla": "99.95%", "notes": ""},
        endpoints=[
            {"id": "tokenize", "method": "POST", "path": "/tokenize",
             "summary": "Mint a shape as ERC-20 token", "auth": "api_key",
             "request_sample": {"shape_id": "qubit_bloch_sphere", "chain": "base", "recipient": "0x..."},
             "response_sample": {"tx_hash": "0x...", "token_id": "42", "contract": "0x..."}},
        ],
        tags=["b2b", "tokenizer", "erc20", "base", "blockchain"],
    ),
    _svc(
        slug="vector-wave-engine",
        name="Vector Wave Engine",
        tagline="FFT + wave solvers for signal processing and mathematical analysis",
        description="High-performance FFT, wavelet transforms, and custom wave equation solvers. Built for UUON's mathematical universe.",
        category="B2B • Mathematical",
        tier="enterprise",
        accent="magenta",
        benefits=["FFT up to 1M points in <10ms", "Wavelet transforms (Haar, Daubechies, Morlet)",
                  "Custom wave equation solver"],
        proof_of_work=[{"metric": "FFT latency", "value": "<10ms @ 1M pts"}, {"metric": "transforms", "value": "Haar, Daubechies, Morlet"}],
        worth={"tier_label": "Enterprise", "price_unit": "per 1k transforms", "price": "$0.60", "sla": "99.9%", "notes": ""},
        endpoints=[
            {"id": "wave-fft", "method": "POST", "path": "/fft",
             "summary": "Fast Fourier Transform", "auth": "api_key",
             "request_sample": {"signal": [0.1, 0.2, 0.3, 0.4], "sample_rate": 44100},
             "response_sample": {"frequencies": [440, 880], "magnitudes": [0.8, 0.3]}},
        ],
        tags=["b2b", "fft", "wave", "signal-processing"],
    ),

    # ── CHAIN DOMAIN ─────────────────────────────────────────────────────────
    _svc(
        slug="multi-chain",
        name="UUON Multi-Chain",
        tagline="Unified multi-chain integration layer — Base, Arbitrum, Optimism, Polygon, Ethereum",
        description="Route reads and writes across supported chains with a single consistent interface. Automatic gas estimation, idempotent writes.",
        category="Chain",
        tier="industrial",
        accent="gold",
        benefits=["Single interface across 5 chains", "Automatic gas estimation", "Chain-agnostic event stream"],
        proof_of_work=[{"metric": "chains", "value": "5"}, {"metric": "avg finality", "value": "2.1 s"}],
        worth={"tier_label": "Industrial", "price_unit": "per 1k reads", "price": "$0.50", "sla": "99.95%", "notes": ""},
        endpoints=[
            {"id": "mc-read", "method": "GET", "path": "/read/{chain}/{contract}",
             "summary": "Read from any supported chain", "auth": "api_key",
             "request_sample": {"chain": "base", "contract": "0xfb9c83432331EAf6f4a9D9488828823587d6f3da"},
             "response_sample": {"result": "1200000000000000000"}},
            {"id": "mc-write", "method": "POST", "path": "/write/{chain}",
             "summary": "Submit a transaction", "auth": "api_key",
             "request_sample": {"chain": "base", "to": "0x...", "data": "0x.."},
             "response_sample": {"tx": "0xdeadbeef", "status": "submitted"}},
        ],
        tags=["chain", "web3", "base", "multichain"],
        repo="https://github.com/UUON-Foundation/API-Gateway",
    ),
]


def _arcade(slug, name, tagline, category, accent, regime, tags=None):
    return {
        "slug": slug, "name": name, "tagline": tagline,
        "category": category, "accent": accent, "regime": regime,
        "status": "locked", "tags": tags or [], "created_at": NOW,
    }


ARCADE_SERVICES = [
    _arcade("dmension", "Δmension", "Mathematical universe — 32 sacred shapes & ERC-20 anchoring",
            "Geometry / Chain", "gold", "Sacred Geometry", tags=["geometry", "web3"]),
    _arcade("hydrogenoid", "Hydrogenoid Atom Engine", "Atomic-scale symbolic primitives",
            "Physics", "magenta", "Atomic Symbolics", tags=["physics"]),
    _arcade("polysculpt", "PolySculpt", "Procedural geometry — fractals, rep-tiles, spirals",
            "Geometry", "cyan", "Procedural Fractals", tags=["geometry", "procedural"]),
    _arcade("fill-theory", "Fill Theory", "The 359.999...° → 0° angular transition",
            "Mathematics", "gold", "Angular Systems", tags=["math"]),
    _arcade("cosmic-forces", "Cosmic Forces", "Five real-time parametric visualization forces",
            "Visualization", "magenta", "Force Fields", tags=["visualization"]),
    _arcade("3dpstudio", "3dP Studio", "Multi-portal creative studio — 3D, AI, math",
            "Creative", "orange", "Creative Studio", tags=["3d", "creative"]),
    _arcade("uuon-c-bot", "UUON_C_Bot", "Cross-service orchestration & telemetry bot",
            "Automation", "cyan", "Orchestration", tags=["bot"]),
]
